name: StringCalculator CI
on: [push]
jobs:
  jest-run:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./
    steps:
      - name: Checkout
        uses: actions/checkout@v2.4.2
      - name: Install dependencies
        run: npm install
      - name: Run Jest
        run: npm run test
